name: Upload to server
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: npm install
      - run: npm run build --if-present
      - run: echo "RewriteBase /" >> build/.htaccess
      - run: echo "RewriteRule ^index\.html$ - [L]" >> build/.htaccess
      - run: echo "RewriteCond %{REQUEST_FILENAME} !-f" >> build/.htaccess
      - run: echo "RewriteCond %{REQUEST_FILENAME} !-d" >> build/.htaccess
      - run: echo "RewriteRule . /index.html [L]" >> build/.htaccess
      - run: echo 'Header set Cache-Control "no-cache, private"' >> build/.htaccess

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: federicodonner.com
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./build/
          server-dir: txcalc.federicodonner.com/public_html/
          dangerous-clean-slate: true
